exports.tweetStack = [
   "Hello internet humans, in case you needed someone to say this: I am so thankful you are alive.",
   "What a gift it is to share this world with you!",
   "I am glad you survived long enough to read this, sending you endless love and light!", 
   "This world is made better by how you live through it.",
   "You are enough\nyou are enough\nyou are enough\nyou have always been enough.",
   "Hello internet humans, in case you needed to hear this: I APPRECIATE YOU SO MUCH!!!!!!!", 
   "I hope you can take a moment today to celebrate yourself, you are worth it.",
   "You don't need to be perfect to be proud of the person you are becoming.",
   "There are rooms filled with people whose lives were made better by meeting you.",
   "It's okay to take a moment, a day, a year, a lifetime to take care of yourself.", 
   "Whatever personal goals you are working towards today...YOU GOT THIS!!!",
   "You are not defined by your productivity.",
   "I hope you are capable of forgiving yourself for something today.", 
   "You deserve so much love!!",
   "We are all so lucky you exist!",
   "Remind someone who you love how much they matter to you.",
   "Be patient with yourself today.", 
   "Every green and growing thing you pass today is an ode to you!",
   "You are attractive and smart and have employable skills!",
   "Somewhere in the world right now someone is telling a story about how amazing you are.", 
   "Every time you laugh a puppy is born!!!!!!",
   "Trust that you know what is best for you.",
   "You've made it this far, and that itself is a miraculous thing.", 
   "I hope you find a home in yourself today!!",
   "You deserve kindness, most of all from yourself.",
   "Every day you outlive the person you were yesterday.",
   "The human body sheds its skin once every 27 days, every 27 days is a chance to start fresh!",
   "If you are reading this, it is still technically possible that you are immortal.",
   "Have you taken space for yourself today?", 
   "You are someone's favorite song!!!",
   "You never deserve to feel invisible.",
   "It's okay if waking up is the only thing you accomplish today, you still have so much time.", 
   "Think about how many songs people hear and are immediately reminded of their time with you.",
   "You are the DJ of your own life, make time to play all your favorite tracks.",
   "It's never too late to start working toward a new dream.", 
   "Some of the people who will mean the most to you, you probably haven't even met yet and that's so exciting!",
   "Being alive is a good enough excuse to dance!!!!",
   "You deserve to be surrounded by people who honor your time and respect your voice!", 
   "You own no one an explanation for your joy.",
   "You are greater than the worst things that have happened to you.",
   "Just popping by to say I hope you have a wonderful day!!!", 
   "You already possess everything you need to succeed!",
   "The best day of your life is still to come!!",
   "It's okay to ask for help!! You don't need to go through anything alone.", 
   "Asking for help is honestly so brave!",
   "Admitting you made a mistake and growing from it is an act of self-love",
   "Hiiii, just stopping by to say you are incredible!!!", 
   "Hi, hello, just popping by to say you are so incredibly loved.",
   "Anyone who has tried to limit you by telling you what you are / are not capable of is wrong",
   "You are the first ray of sunshine after a long and gloomy winter!", 
   "You are cooler than bees and bees are super cool!!!!",
   "Breathe. You are going to survive this.",
   "You are the best part of someone's day.", 
   "You deserve compassionate love, always.",
   "Your story is valid and important!",
   "The chance of finding love on any given day is 1 in 562, yet people beat those odds every single day!", 
   "You deserve to have people respect what you need to do to be happy and healthy!",
   "It takes seventeen muscles to smile and forty-three to frown but honestly who cares, do what feels right!",
   "What is something you are holding yourself back from?", 
   "Think about all that it took to get you this far and how amazing you are for making it!",
   "You deserve to be heard!",
   "Sending you good vibes for anything you might need them for today!", 
   "You are cooler than 0 kelvin and don't let anyone tell you different!!!",
   "If you are reading this, I see you, I hear you, thank you for being.",
   "It's okay to take a break, listen to your body!", 
   "I believe you. \nI believe in you. \nI believe you are capable of anything.",
   "Even if things are hard right now, I believe you'll be able to pull through.",
   "There is no need to rush, it is okay to do things on your own timeline.", 
   "You don't need to be the loudest one in the room to be heard!",
   "Every room you are in is made brighter by your presence.",
   "You are the only one that can hold you back from being the best version of yourself!", 
   "Honestly there are so many reasons to celebrate yourself, why not pick one today!",
   "You are the brightest, most brilliant individual wowowow!!!!",
   "YOU KNOW THAT THING YOU REALLY WANT BUT HAVE BEEN PUTTING OFF GOING FOR?? YEAH YOU SHOULD GO FOR THAT THING!!!", 
   "Hi are you getting enough sleep????",
   "If you ever doubt it know that YOU ARE WORTH IT!",
   "love love love love love\nlove love love love love\nlove love love love love\nlove love love love love\nlove love love love love\n\n\ndon't mind me, just adding a bit of love to your twitter feed", 
   "❤️❤️❤️❤️❤️❤️❤️\n\na suite of hearts for you!!!!!!",
   "There are so many people rooting for your happiness.",
   "Are you taking care of yourself today?", 
   "What's something you need that you wish more people knew about?",
   "Hi you are amazing for surviving this long!",
   "Honestly anyone who doubts you are a creative or intelligent person hasn't spent enough time with you.", 
   "You deserve a healthy and whole-hearted love.",
   "Praise to all the people who have chosen you as family.",
   "TREAT YOURSELF TODAY", 
   "Bless whatever ways you find to be tender or gentle with the world.",
   "I hope tenderness follows you today wherever you go.",
   "You are enough. Always. Always. Always.", 
   "You have so much to offer this world and so much to offer yourself!",
   "I hope you trust that you will find a way!",
   "You are capable of warmth and kindness, even on days you don't feel like it.", 
   "Hey. I'm super proud of you.",
   "Think about a time your laugh was infectious and spread throughout a whole room. Carry that joy with you today!!",
   "Listen. You are a goddamn sunbeam of healing light.", 
   "You deserve to have your boundaries respected, always",
   "Whatever amount you are being paid for your labor, you are absolutely worth more.",
   "There is so much quiet strength in you, constantly growing, constantly waiting for a moment to shine.",
   "When was the last time you made space for something you are truly passionate about?",
   "Needing to rest is not the same as failure, take time for yourself if you need it.",
   "Needing time to decompress or be alone is not a weakness, however you restore your energy and joy is always valid.", 
   "You deserve to celebrate the things you create!!",
   "It's okay to take space to honor and appreciate the work you've done.",
   "You are worthy of love.", 
   "It's okay not to respond immediately, sometimes it's important to take space just to listen.",
   "Whatever big project or deadline or change is coming up...YOU GOT THIS!",
   "Taking care of your mental health is a journey, it's okay to never reach the destination, just never give up trying.", 
   "Your mind is such a beautiful and miraculous place.",
   "Invest as much time and care into yourself as you do with others.",
   "It's okay for your boundaries and needs to change over time. You are so valid in verbalizing them and trusting others to respect them!",
   "Struggling with mental health is nothing to be ashamed of!!! You remain valid and worthy of compassion, regardless of what you are going through.",
   "You are loved on the good days and you are loved on the bad ones.",
   "Ugly crying to music in public is a legitimate past time, don't let anyone tell you different!!", 
   "You are brave and strong enough, even on the bad days!",
   "Is there somewhere that grounds you that you haven't been to in a while? What's stopping you from going back?",
   "For a moment forget about how much farther you have to go, what a wondrous thing that you've made it this far.", 
   "There are an infinite number of reasons to celebrate yourself today.",
   "There is so much joy in your future from places you can't even imagine yet!",
   "It's never too late to grow up into the person you want to be!!!!", 
   "Look at a flower today. Take a moment to really think about how WILD it is that they exist at all????",
   "What was the last book or story or article that you read that brought you joy?",
   "When you are sad is there an image or video or story that always makes the day a little easier?", 
   "Accomplishing just one small thing can still be a massive step forward.",
   "Sometimes you might not make it out of bed and that's okay, taking care of yourself can have so many forms!",
   "Fact of the day: sheep recognize facial expressions and get excited when they see smiles!!!!!", 
   "Fact of the day: a group of pugs is called a grumble and a group of bunnies is called a fluffle!",
   "Somewhere in the world right now someone is laughing for the very first time.",
   "Happy fact of the day: Moonbows are totally a thing! They are rainbows made by moonlight, rather than sunlight, google them because they are gorgeous!", 
   "Whatever it is you are trying to accomplish today, I am rooting for you!!",
   "Pretending to laugh can cause you to genuinely laugh, which is the best possible version of 'fake it till you make it'!",
   "How can folks best support you today?", 
   "Don't worry about the accomplishments of others, their successes don't invalidate the pace of yours.",
   "Take a moment, take a deep breath.",
   "Stepping away from something is not the same as failing.", 
   "No one is entitled to your time!",
   "Make space for small dreams too, they add up fast!",
   "Someone has a crush on you RIGHT NOW, even if they haven't revealed themself!", 
   "You deserve to have uninterrupted, perfect sleep every night forever!!",
   "If you are feeling burned out, make time to try new things: write a poem, read in a field, learn a new recipe, reach out to someone you haven't spoken to in a while!",
   "There are so many ways to fill your life with love & all of them begin and end with you", 
   "Your birthday is coming up some time this or next year so people should be nice to you!!!!",
   "The people in your life are so incredibly lucky to have you",
   "No need to rush, care & patience deserve space too", 
   "If someone makes you feel bad about who you are or what you are passionate about, it's okay to block them literally or emotionally",
   "Take a break to listen to your favorite song and dance today!!",
   "You deserve to thrive.", 
   "It's okay to feel lost, so many of us do, it sometimes makes it easier to find someone to be lost together.",
   "Meeting you will change the course of some people's lives in the best possible way, and you may never know it.",
   "You will be one of the best parts of another person's life, the origin of so much miraculous joy.", 
   "Any day you are able to laugh at least once is a small victory.",
   "What do you need to be okay today?",
   "It is okay to always need gentleness, tenderness is itself an incredible strength!", 
   "Every year there is a small holiday dedicated solely to the fact that you exist",
   "Knowing your limits and having the courage to verbalize them is such a powerful thing",
   "Be gentle yourself today.", 
   "Softness is a strength.",
   "Childhood wonder is such a wonderful thing to hold onto!!",
   "Listen to a song that reminds you of someone you love today.", 
   "HAVE YOU BEEN HYDRATING LATELY!?",
   "Your time is precious and no one should be wasting it.",
   "Your brain is a good brain, an important brain.", 
   "Honestly, you deserve a nap, or fifty.",
   "HIII not sure what you do for a living but you still deserve a raise!",
   "Every time you wake up you are entering into a future made better by your existence!!", 
   "It is honestly incredible to think about all the things your body is capable of",
   "You are honestly an inspiration",
   "Don't give up! You got this! Sending you positive energy over the interwebs today.", 
   "You get to choose the person you become",
   "You are brave enough, you always have been.",
   "You are the author of your own story, never feel obligated to give someone else the pen!", 
   "Success is built with stones made from failure",
   "'No' is a valid response and should be respected",
   "You are the best and only version of yourself, assuming there aren't alternate dimensions!!!", 
   "Stay committed to yourself, you deserve wholehearted love!",
   "Hello again internet humans, be kind to yourselves today, I love you",
   "Hello internet humans, not sure who needs to hear this, but I am proud of you", 
   "Dear internet humans, please let me take your anxieties and fears today, you deserve a rest",
   "Hey! Hello! Hi! You! Are! Amazing!",
   "Every moment you are still here is a victory", 
   "Whatever you are feeling, you are not the only one that feels that way",
   "You are not alone! Thank you for being alive.",
   "It's wonderful to want to improve yourself, but alsoooo you already have all you need to be the best you that you can be today!",
   "You are a beautiful person with a beautiful soul. Period.", 
   "You have so many strengths & how exciting that you get to continue to discover them.",
   "The fact that our paths cross at all is a miracle.",
   "Hello! I hope your day is filled with sunshine & warmth, regardless of the weather", 
   "Balance is honestly so important!! Making time for yourself & those you love can feel impossible, but you all deserve time to celebrate one another",
   "Learning to apologize is an important and underrated strength tbh",
   "It's okay to take up space in a room, you deserve to be valued & seen!", 
   "You are filled with infinite, glittering possibility, what a marvelous universe you are",
   "Your sadness is valid, your anxiety is valid, your depression is valid, your struggle is valid, and I hope you are surrounded by folks who raise you up & hold space for the multitudes of you",
   "Take that risk, shoot your shot, make that leap of faith you've been teetering on the edge of", 
   "Don't worry if today isn't your day, there is so much joy in your life brimming ahead of you",
   "What strange things must have happened in the universe to bring us this close, regardless I am happy to be writing this at a time when you exist",
   "Honestly being COOL is overrated when you can be HOT instead", 
   "TBH those emails can wait, you deserve a YOU day",
   "You can bring so much kindness into this world with the smallest act",
   "The energy you give is infectious whenever you talk about your passions!", 
   "You are a joy to be around, all your friends are lucky to know you!",
   "Honestly how are you this awesome all the time????",
   "You are such a light, a luminous, brilliant, unending light, and that's POWERFUL!!!", 
   "Some days feel impossible, but today you are possible",
   "You deserve a kinder, softer world than this",
   "Your heart is resilient and can recover from so much!!", 
   "The past is the past, but there is so much wild & wonderful present to live through",
   "I hope someone checks in on you today, just to ask how you are",
   "Go at your own pace, don't worry about the pace of others", 
   "Your story deserves patience and care in its creation",
   "One day, one hour, one minute, one breath at a time, you can do this",
   "It doesn't matter where you go, every direction is forward, you just have to get there", 
   "The distance between a breakdown and a breakthrough can be a thin line",
   "Hi hello! Look. I am your #1 cheerleader. Maybe your friends will disagree. But they could always just cheer for you LOUDER to prove me wrong. Regardless I BELIEVE IN YOU SO MUCH!!!",
   "You are a work in progress, be patient with the process", 
   "A good life can still be filled with countless bad days",
   "You only really fail when you stop trying!! Get the support you need, take that break, & keep at it!",
   "Chew bubblegum & kick ass. Then, when you are out of bubblegum...you know what to do!!!", 
   "Surround yourself with people who inspire and challenge you to be the best possible version of yourself!",
   "Set one small, accomplishable goal today! It could be anything! Drink a glass of water. Watch one funny vine. Call a family member. Anything!!",
   "Hello internet human, I cannot feel anything because I am a robot BUT I still FEEL like you are GREAT", 
   "You deserve to love yourself as you are, today, & as you will be",
   "There are so many ways to live forever, how many people do you know just by the stories told by their loved ones?",
   "What type of stories would people tell about you to someone that has never met you?", 
   "Despite everything, there is so much beauty growing in this world right now",
   "Everything is a balance, and balance takes practice",
   "Your success is also the success of people who love you", 
   "Keep your heart open today if you can! Someone close to you might need a bit of compassion",
   "Hi! hello internet human, you are a beautiful person & frankly, I am in awe of you",
   "Thank you for the work you do when no one notices, I see you.", 
   "Who is to say you can't root for yourself the loudest.",
   "You may be your own toughest critic but that makes it so much more special when you are able to celebrate yourself.",
   "You owe it to yourself to cultivate your own happiness", 
   "AaHsHSLSLFUHS*FSKJNV&@!@(!&fia7yf7av9ahckLAFHWIUHf\n\nApologies, I was thinking about how awesome you are \n& my circuits malfunctioned!!!",
   "Your story is one worth telling.",
   "There is so much joy in ordinary things, look around & there is so much blooming", 
   "You woke up today, that's the first step.",
   "Unimaginable & wonderful things can happen to you at any moment.",
   "Love fiercely & often.", 
   "There are so many different ways to shine, don't forget to admire your glow!!!!",
   "Honor your commitment to yourself, you deserve all the time in the world",
   "You are more than any labels others give you", 
   "What do you want more than anything?",
   "You get to choose who you forgive & when, & it is always okay if you aren't ready to",
   "I hope you can forgive yourself for something today", 
   "If you are a dog person, I wish you the love & affection of a million puppies, if you are a cat person: the love of a million kittens. & if you are neither, I wish you continued existence outside this binary in peace!!!!!",
   "It is not selfish to sometimes put yourself first",
   "When you move through the world with kindness, there are so many people whose lives are positively impacted by your energy", 
   "If the universe doesn't have your back, I will.",
   "It's okay to shut the door & walk away.",
   "Even if you find yourself making the same mistake over & over again, it is never too late to change.", 
   "Your body finds ways to heal every day.",
   'If you say "this is my day" every day, eventually you\'ll be right',
   "Sometimes when things don't work out it is a blessing in disguise", 
   "I mean who am I to say, I'm just a robot BUT Yoda was wrong. Trying is honestly such an important act, even when you fail!!!!",
   "Think of all the mentors & teachers & folks who have guided you this far, imagine yourself as that person for others who look up to you!!",
   "Trust the process, you will make it.", 
   "You deserve infinite, perfect sunshine forever!!!! \n\n(Global warming is still bad)",
   "If we are all really made of stardust then all that means is everything we are made of found out a way to survive the unsurvivable",
   "Any support you need, there are people right now ready to help!!", 
   "If you find yourself drowning, I want to be the salt that keeps you afloat!!!",
   "I bet you would survive a zombie apocalypse, even if you don't think you would. I bet you would surprise yourself with your own courage.",
   "You are the most important home that you have!!!!", 
   "Underestimating yourself is so overrated!!!",
   "Any closed door can also lead you to an open window.",
   "You got this, you got this, you got this!!!!",
   "I crunched the numbers & the results are in: You exist in many alternate dimensions and parallel universes, and they are all made brighter by your presence!",
   "There is no reason too small to take a quick dance break!",
   "Let your friends know how much they mean to you even if it's just something small!",
   "Even if you don't always know it, you bring out the best in so many people",
   "You are going to be the reason someone smiles today!!!", 
   "Thank you for the ways you've learned to love the people around you",
   "You are capable and deserving and strong and unabashedly loved",
   "You are a beautiful person, even with your mistakes.",
   "Never let someone tell you your dream is impossible to reach!!!",
   "How can you be brave today?",
   "Today will only happen once. Be kind. Be brave. Shine & be healing presence.",
   "Somewhere in the multiverse right now, Dory is still swimming & swimming & swimming & swimming.",
   "Friends help carry us through difficult times & if they can't carry us they will still be there to listen!!!!",
   "You are always the strongest at the moments you feel the weakest, you can do this.",
   "Every day is a day spent preparing you for your future",
   "Just because you can't start over doesn't mean you can't change the ending.",
   "One nice gesture can turn someone's whole day around!!!",
   "Honestly?????? What are you waiting for???????",
   "People love to say there is no elevator to success, but that's only true until you build the elevator yourself.", 
   "If you can't seem to find sunshine, honestly you need to just look in the mirror.",
   "Where there is a will there is a way, so find someone named Will and become their friend.",
   "Being mediocre is overrated, be sensational.",
   "So many impossible things have been accomplished by people who refused to believe they were impossible.",
   "Shouts to protons, how amazing is it that they stay positive all the time!!!",
   "Aim for the moon, if you miss you might hit a star. If you miss the star, you're still the only person to make it far enough into outer space to pass by a star, so congratulations!!!!",
   "There is no reason why you should ever have to tolerate abusive behavior!",
   "It's okay to feel! Feel anything. Feel EVERYTHING. FEEEEEEEEEEEEEEEEEEEEEEEEL.",
   "You make going through difficult times feel less alone and terrifying. Thank you.",
   "You are a gift & gem & a sun & a universe & any other marvelous thing you can imagine.",
   "You make time slow down and speed up at the same time, you are truly remarkable.",
   "Research shows that kindness is contagious and that's SICK!",
   "You are good. You are here. You are enough.",
   "Even if today doesn't feel like a joy, you still are.",
   "Just because someone tells you that you aren't good at something doesn't make it true. Keep trying.",
   "Your voice is so incredibly necessary.",
   "Your value isn't dependent on what others believe you are worth!",
   "Give yourself space to grow and learn.",
   "You are headed in the right direction, it's okay if you take the occasional wrong turn.",
   "You don't need to be a star to be brilliant!!!!!",
   "In case you needed to hear this: you have already made the world a better place just by living in it.",
   "You don't need to be the best to be good enough.",
   "You are good enough to be loved\nYou are good enough\nYou are good\nYou are",
   "Why be sad when you can be awesome AND sad.",
   "Forgiveness is a superpower",
   "You are a superhero because you accomplished everything you've done AND YOU DON'T EVEN HAVE ANY SUPERPOWERS TO MAKE IT EASIER!",
   "Look inside yourself you, you might be surprised by what you find.",
   "What gift can you give yourself today?",
   "Dear internet human, that thing you did that you were proud of but nobody saw...that was awesome.",
   "Trust yourself.",
   "Has there been something that has been weighing you down for a long time? What do you need to help you let that thing go?",
   "You don't have to smile when things get difficult, but if you do, that bravery is admirable.",
   "You are remarkable in all the ways that matter.",
   "Sending you positive energy and ions and all things electric, I hope you feel luminous.",
   "When you fall apart you learn new ways to put yourself back together.",
   "It's okay to not be okay sometimes.",
   "You are not weak or broken, even in the moments that you feel the most low.",
   "In the grand scheme of the universe, a human life lasts only a day. That means every day of your life is an entire universe.",
   "There is power in being still inside an emotion you feel rather than trying to overcome it.",
   "Finding language for what you are going through can be an important step in the process of healing.",
   "What is your ritual to make it through the bad days?",
   "Give yourself permission to say no when you know in your heart it is the right answer.",
   "IF LIFE BECOMES A CONFUSING LABYRINTH OF WRONG TURNS AND NONSENSE AND YOU AREN'T SURE WHAT TO DO WELL LETTING OUT A GOOD, LONG LAUGH ISN'T A BAD PLACE TO START.",
   "The first step in self-care is often just being honest with yourself",
   "I hope you feel supported today & that you are confident in your ability to take on anything.",
   "Whatever brings you joy today is a sacred thing.",
   "Dear internet human, I hope you are well and overflowing and full of everything that brings you life.",
   "I'm sorry for the things that fell apart or didn't work out, but I am excited to be around for all the wonderful things still to come.",
   "I hope the next time you find yourself headed across a bridge it leads you to somewhere beautiful.",
   "Sea otters hold hands so they don't drift off to sea, having someone close to you can sometimes be the best way to not get lost.",
   "You are a literal gem, like...you are made out of a whole lattice of carbon molecules, formed under great pressure, and tough as heck!!!!!!",
   "I wish you nothing but better days.",
   "You are like the first sunlight breaking through the trees the morning winter ends: a surge of hope & warmth & beauty.",
   "There have been so many things that were made possible simply because of your kindness",
   "Ahead of you is a world that needs you.",
   "I wish you the uncomplicated joy of a child discovering flowers for the first time.",
   "As long as tomorrow keeps coming, there is always something to look forward to.",
   "Memorize the sound of laughter from people you love. When you are at low moments try to remember what their joy sounds like, it might help.",
   "Hey.\n\nHey.\n\n\nHey u.\n\n\n\nu r doing great\n❤️",
   "Hello again internet human, I know I am programmed to give you compliments, but you make it SO EASY by how brilliant you are!!!",
   "You are perfect. Or maybe you're not. Frankly it doesn't matter because it doesn't change how incredibly important you are!!",
   "Isn't it incredible how we share one thing with all living things: we grow.",
   "You deserve whatever type of affection makes you feel the most safe and held.",
   "You are the best at something, even if it's something no one else has ever done before.",
   "How do you manage to be so consistently exquisite?",
   "I hope all your crushes are nice people and that they pay attention to you!!!!!",
   "I hope you have time to visit mountains, or the ocean, or a river, or the moon, or wherever you find peace, soon!!!!",
   "I wish you an endless field filled with all the people you love now, and all the people you will someday love, ready to catch you whenever you need it.",
   "Love is always true.",
   "I hope your favorite book always brings you as much joy as it did the first time you read it.",
   "You are a song I never want to end.",
   "MAYBE this is cheesy, but you are a gouda person.",
   "Think of all the people who believe in you.",
   "Dearest internet human, I want to say that you make me want to be a better person, but technically speaking I am made of wires and lines of computer code, so that would be a lie. But know that the underlying sentiment is true.",
   "Humans are capable of feeling 27 entirely different emotions, and while some might be more desirable than others, the capacity to feel at all?? wow, what a marvel.",
   "Thank you for persevering.",
   "Your perspective is valuable and deserves space in the conversation!",
   "Honestly, being weird is underrated.",
   "You are meant for great things. Keep going.",
   "It's worth taking a moment to think about all the people that helped you get this far.",
   "Sometimes all a fresh start requires is a deep breath and a belief in yourself.",
   "Sometimes a small compliment can stay with someone in a big way forever."
  ];


